# Paths are based on directory "Servers/{.*}/"

version: "2.4"
services:
  ARKServer:
    build: ../../DockerBuild
    image: arksurvivalevolved
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    env_file:
      - ./.env
    volumes:
      - ARKServerFiles:/ARK/Server:rw
      - ../../ClustersTransfers:/ARK/Server/ShooterGame/Clusters:rw
      - ./Saved:/ARK/Server/ShooterGame/Saved:rw
      - ./StartupLogs:/ARK/Server/StartupLogs:rw
    ports:
      - ${ARKSERVER_PUBLICIP:?ARKSERVER_PUBLICIP}:${ARKSERVER_PORT:?ARKSERVER_PORT}:${ARKSERVER_PORT:?ARKSERVER_PORT}/udp
      - ${ARKSERVER_PUBLICIP:?ARKSERVER_PUBLICIP}:${ARKSERVER_PORTPLUS:?ARKSERVER_PORTPLUS}:${ARKSERVER_PORTPLUS:?ARKSERVER_PORTPLUS}/udp
      - ${ARKSERVER_PUBLICIP:?ARKSERVER_PUBLICIP}:${ARKSERVER_QUERYPORT:?ARKSERVER_QUERYPORT}:${ARKSERVER_QUERYPORT:?ARKSERVER_QUERYPORT}/udp
      - ${ARKSERVER_PUBLICIP:?ARKSERVER_PUBLICIP}:${ARKSERVER_RCONPORT:?ARKSERVER_RCONPORT}:${ARKSERVER_RCONPORT:?ARKSERVER_RCONPORT}/tcp

volumes:
  ARKServerFiles:
